services:
  # =========================
  # Cibles vulnérables
  # =========================
  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    ports:
      - "8080:80"
    networks:
      labnet:
        ipv4_address: 172.30.0.10
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  juice:
    image: bkimminich/juice-shop
    container_name: juice
    ports:
      - "3000:3000"
    networks:
      labnet:
        ipv4_address: 172.30.0.20
    restart: unless-stopped

  bwapp:
    image: raesene/bwapp
    container_name: bwapp
    ports:
      - "8081:80"
    networks:
      labnet:
        ipv4_address: 172.30.0.30
    restart: unless-stopped

  metasploitable2:
    image: tleemcjr/metasploitable2
    container_name: metasploitable2
    tty: true
    stdin_open: true
    ports:
      - "2222:22"
      - "2121:21"
      - "8083:80"
      - "13060:3306"
    networks:
      labnet:
        ipv4_address: 172.30.0.40

  mutillidae:
    image: citizenstig/nowasp
    container_name: mutillidae
    ports:
      - "8082:80"
    networks:
      labnet:
        ipv4_address: 172.30.0.50
    restart: unless-stopped

  # =========================
  # Modules Kali
  # =========================
  base:
    build: ./lab/base
    image: kali-base:latest
    container_name: kali-base
    tty: true
    stdin_open: true
    networks:
      labnet:
        ipv4_address: 172.30.0.100
    cap_add:
      - NET_RAW
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./scripts:/workspace/scripts
      - ./wordlist:/workspace/wordlists
      - ./reports:/reports
      - ./vpn:/vpn

  recon:
    build: ./lab/recon
    image: kali-recon:latest
    container_name: kali-recon
    tty: true
    stdin_open: true
    networks:
      labnet:
        ipv4_address: 172.30.0.110
    cap_add:
      - NET_RAW
      - NET_ADMIN
    volumes:
      - ./scripts:/workspace/scripts
      - ./wordlist:/workspace/wordlists
      - ./reports:/reports
    depends_on:
      - base

  exploit:
    build: ./lab/exploit
    image: kali-exploit:latest
    container_name: kali-exploit
    tty: true
    stdin_open: true
    networks:
      labnet:
        ipv4_address: 172.30.0.120
    cap_add:
      - NET_RAW
      - NET_ADMIN
    volumes:
      - ./scripts:/workspace/scripts
      - ./wordlist:/workspace/wordlists
      - ./reports:/reports
      - ./vpn:/vpn
    depends_on:
      - base

  web:
    build: ./lab/web
    image: kali-web:latest
    container_name: kali-web
    tty: true
    stdin_open: true
    ports:
      - "8090:8080"
      - "8091:8081"
    networks:
      labnet:
        ipv4_address: 172.30.0.130
    volumes:
      - ./scripts:/workspace/scripts
      - ./wordlist:/workspace/wordlists
      - ./reports:/reports
    depends_on:
      - base

  postex:
    build: ./lab/postex
    image: kali-postex:latest
    container_name: kali-postex
    tty: true
    stdin_open: true
    networks:
      labnet:
        ipv4_address: 172.30.0.140
    cap_add:
      - NET_RAW
      - NET_ADMIN
    volumes:
      - ./scripts:/workspace/scripts
      - ./wordlist:/workspace/wordlists
      - ./reports:/reports
    depends_on:
      - base

  cracking:
    build: ./lab/cracking
    image: kali-cracking:latest
    container_name: kali-cracking
    tty: true
    stdin_open: true
    networks:
      labnet:
        ipv4_address: 172.30.0.150
    volumes:
      - ./scripts:/workspace/scripts
      - ./wordlist:/workspace/wordlists
      - ./reports:/reports
    depends_on:
      - base

  network:
    build: ./lab/network
    image: kali-network:latest
    container_name: kali-network
    tty: true
    stdin_open: true
    networks:
      labnet:
        ipv4_address: 172.30.0.160
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./scripts:/workspace/scripts
      - ./wordlist:/workspace/wordlists
      - ./reports:/reports
    depends_on:
      - base

  misc:
    build: ./lab/misc
    image: kali-misc:latest
    container_name: kali-misc
    tty: true
    stdin_open: true
    networks:
      labnet:
        ipv4_address: 172.30.0.170
    volumes:
      - ./scripts:/workspace/scripts
      - ./wordlist:/workspace/wordlists
      - ./reports:/reports
      - ./vpn:/vpn
    depends_on:
      - base

networks:
  labnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16